language: ruby

services:
  - postgresql


rvm:
  - 2.3.1

bundler_args: --without test 

cache:
  bundler: true

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
 - psql -c 'create database tackletracker_test;' -U postgres
 - bundle update
