# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

TackleType.create(name: 'Sonar', tackle_category: 'Electronics')
TackleType.create(name: 'Shoes', tackle_category: 'Clothing')
TackleType.create(name: 'Lure Kit', tackle_category: 'Lures')
TackleType.create(name: 'Fishing Kite', tackle_category: 'Accessories')
TackleType.create(name: 'Minnow Lure', tackle_category: 'Lures')
TackleType.create(name: 'Boat Controls', tackle_category: 'Boating')
TackleType.create(name: 'Buzzbait Lure', tackle_category: 'Lures')
TackleType.create(name: 'Lever Drag Reel', tackle_category: 'Reels')
TackleType.create(name: 'Surf Rod', tackle_category: 'Rods')
TackleType.create(name: 'Life Vest', tackle_category: 'Boating')
TackleType.create(name: 'Panfish Bait', tackle_category: 'Lures')
TackleType.create(name: 'Spoon', tackle_category: 'Lures')
TackleType.create(name: 'Boat', tackle_category: 'Boating')
TackleType.create(name: 'Conventional Non-Level Wind Reel', tackle_category: 'Reels')
TackleType.create(name: 'Pole Rod', tackle_category: 'Rods')
TackleType.create(name: 'Bait Trap', tackle_category: 'Accessories')
TackleType.create(name: 'Oars', tackle_category: 'Boating')
TackleType.create(name: 'Underwater Camera', tackle_category: 'Electronics')
TackleType.create(name: 'Leader', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Fly Rod', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Fish Finder', tackle_category: 'Electronics')
TackleType.create(name: 'Gloves', tackle_category: 'Clothing')
TackleType.create(name: 'Waders', tackle_category: 'Clothing')
TackleType.create(name: 'Tackle Bag', tackle_category: 'Accessories')
TackleType.create(name: 'Trolling Motor Accessory', tackle_category: 'Boating')
TackleType.create(name: 'Rod Accessory', tackle_category: 'Accessories')
TackleType.create(name: 'Float Tube', tackle_category: 'Boating')
TackleType.create(name: 'Spinning Rod', tackle_category: 'Rods')
TackleType.create(name: 'Bimini', tackle_category: 'Boating')
TackleType.create(name: 'Shirts', tackle_category: 'Clothing')
TackleType.create(name: 'Charger', tackle_category: 'Boating')
TackleType.create(name: 'Electric Reel', tackle_category: 'Reels')
TackleType.create(name: 'Spinning Reel', tackle_category: 'Reels')
TackleType.create(name: 'Fly Outfit', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Tournament Gear', tackle_category: 'Accessories')
TackleType.create(name: 'Ruler', tackle_category: 'Accessories')
TackleType.create(name: 'Personal Locator Beacon', tackle_category: 'Electronics')
TackleType.create(name: 'Hard Bait Lure', tackle_category: 'Lures')
TackleType.create(name: 'Catfish Bait', tackle_category: 'Lures')
TackleType.create(name: 'Trolling Motor', tackle_category: 'Boating')
TackleType.create(name: 'Rain Gear', tackle_category: 'Clothing')
TackleType.create(name: 'GPS Device', tackle_category: 'Electronics')
TackleType.create(name: 'Soft Bait Lure', tackle_category: 'Lures')
TackleType.create(name: 'Fly Reel', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Jig Head', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Trolling Accessory', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Swivels', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Top Water Lure', tackle_category: 'Lures')
TackleType.create(name: 'Fly Line', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Lights', tackle_category: 'Boating')
TackleType.create(name: 'Sinkers', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Reel Accessory', tackle_category: 'Accessories')
TackleType.create(name: 'Fillet Knife', tackle_category: 'Accessories')
TackleType.create(name: 'Hook Tool', tackle_category: 'Accessories')
TackleType.create(name: 'Conventional Rod', tackle_category: 'Rods')
TackleType.create(name: 'Fishing Lights', tackle_category: 'Accessories')
TackleType.create(name: 'Hooks', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Species Specific Rod', tackle_category: 'Rods')
TackleType.create(name: 'Dock Supplies', tackle_category: 'Boating')
TackleType.create(name: 'Shorts', tackle_category: 'Clothing')
TackleType.create(name: 'Fly Tippet', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Camera', tackle_category: 'Electronics')
TackleType.create(name: 'Fishing Headlamps', tackle_category: 'Accessories')
TackleType.create(name: 'Rod Holders', tackle_category: 'Accessories')
TackleType.create(name: 'Carp Bait', tackle_category: 'Lures')
TackleType.create(name: 'Fly Fishing Accessory', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Lure Building Accessory', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Anchor', tackle_category: 'Boating')
TackleType.create(name: 'Paddles', tackle_category: 'Boating')
TackleType.create(name: 'Line Tool', tackle_category: 'Accessories')
TackleType.create(name: 'Motor Accessory', tackle_category: 'Boating')
TackleType.create(name: 'Jerkbait', tackle_category: 'Lures')
TackleType.create(name: 'Bait Casting Reel', tackle_category: 'Reels')
TackleType.create(name: 'Pliers', tackle_category: 'Accessories')
TackleType.create(name: 'Fillet Accessory', tackle_category: 'Accessories')
TackleType.create(name: 'Sunglasses', tackle_category: 'Accessories')
TackleType.create(name: 'Floats', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Bait Bucket', tackle_category: 'Accessories')
TackleType.create(name: 'Fly Fishing Apparel', tackle_category: 'Clothing')
TackleType.create(name: 'Tackle Rigs', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'General Tool', tackle_category: 'Accessories')
TackleType.create(name: 'Navigation', tackle_category: 'Electronics')
TackleType.create(name: 'Hats', tackle_category: 'Clothing')
TackleType.create(name: 'Stabilizers', tackle_category: 'Boating')
TackleType.create(name: 'Fly Tying Supplies', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Canoe', tackle_category: 'Boating')
TackleType.create(name: 'Trolling Lure', tackle_category: 'Lures')
TackleType.create(name: 'Jig Lure', tackle_category: 'Lures')
TackleType.create(name: 'Casting Rod', tackle_category: 'Rods')
TackleType.create(name: 'Offshore Rod', tackle_category: 'Rods')
TackleType.create(name: 'Tackle Components', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Spinnerbait', tackle_category: 'Lures')
TackleType.create(name: 'Line', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Pants', tackle_category: 'Clothing')
TackleType.create(name: 'Ice Fishing Accessory', tackle_category: 'Accessories')
TackleType.create(name: 'Boat Cover', tackle_category: 'Boating')
TackleType.create(name: 'Radar', tackle_category: 'Electronics')
TackleType.create(name: 'Scale', tackle_category: 'Accessories')
TackleType.create(name: 'Batteries', tackle_category: 'Boating')
TackleType.create(name: 'Marker Buoy', tackle_category: 'Accessories')
TackleType.create(name: 'Fly Leader', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Map Card', tackle_category: 'Electronics')
TackleType.create(name: 'Pontoon', tackle_category: 'Boating')
TackleType.create(name: 'Line Counter Reel', tackle_category: 'Reels')
TackleType.create(name: 'Grub Lure', tackle_category: 'Lures')
TackleType.create(name: 'Popper Lure', tackle_category: 'Lures')
TackleType.create(name: 'Conventional Level Wind Reel', tackle_category: 'Reels')
TackleType.create(name: 'Snaps', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Gauges', tackle_category: 'Boating')
TackleType.create(name: 'Fuel Tank', tackle_category: 'Boating')
TackleType.create(name: 'Tackle Box', tackle_category: 'Accessories')
TackleType.create(name: 'Attractants', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Lure Mold', tackle_category: 'Terminal Tackle')
TackleType.create(name: 'Flies', tackle_category: 'Fly Fishing')
TackleType.create(name: 'Gaff', tackle_category: 'Accessories')
TackleType.create(name: 'Net', tackle_category: 'Accessories')
TackleType.create(name: 'Kayak', tackle_category: 'Boating')
TackleType.create(name: 'Footwear', tackle_category: 'Clothing')
